# Generated by Django 4.2.1 on 2023-05-08 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asosiy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='img',
            name='img',
            field=models.FileField(upload_to=''),
        ),
    ]
