# Generated by Django 4.2.1 on 2023-05-08 04:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asosiy', '0002_alter_img_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infostudent',
            name='img',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='asosiy.img'),
        ),
    ]
