# Generated by Django 4.2.1 on 2023-05-08 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asosiy', '0006_alter_img_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='infostudent',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='asosiy.student'),
        ),
    ]
