# Generated by Django 4.2.1 on 2023-05-11 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asosiy', '0008_alter_img_img_alter_student_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='img',
            name='img',
            field=models.ImageField(null=True, upload_to='ava'),
        ),
    ]
